### ISSUE TITLE
Simplify settings

### ISSUE THREAD

**Issue by tomdyson** [torchbox/wagtail-headless-preview#1]
I vote for a single `HEADLESS_PREVIEW_CLIENT_URLS` setting, rather than supporting both `HEADLESS_PREVIEW_CLIENT_URLS` and `HEADLESS_PREVIEW_CLIENT_URL`.

**Comment by zerolab** [comment]
Done in 415c6a3a530675051ff64d7a9d8de6b6dcb93c28
