### ISSUE TITLE
Is there a way to replace the "View Draft" button to "Preview" in the page list?

### ISSUE THREAD

**Issue by diegoleft** [torchbox/wagtail-headless-preview#12]
<img width="1044" alt="Captura de Pantalla 2020-04-19 a la(s) 19 39 23" src="https://user-images.githubusercontent.com/3319025/79701748-eac84780-8275-11ea-9496-f5b1d01c0214.png">

**Comment by zerolab** [comment]
"view draft" uses the same mechanism as preview under the hood, so you should be covered.
if you do want to change it, do look at https://docs.wagtail.io/en/stable/reference/hooks.html#construct_page_listing_buttons

Given this is a Wagtail core specific question, will close this issue.
