### ISSUE TITLE
Live Preview Not working (Probably Routing Issue)

### ISSUE THREAD

**Issue by uroybd** [torchbox/wagtail-headless-preview#14]
The live preview URL is rendering with the wrong template. It should render with the template this package provides. Instead it is rendering using the template I use for `wagtail.urls`.

**Comment by zerolab** [comment]
Hey @uroybd, thank you for submitting the issue.
I am afraid there is not enough information for us to go on with here. Did you follow the setup instructions? Do regular previews (i.e. `HEADLESS_PREVIEW_LIVE = False`) work as expected?

**Comment by uroybd** [comment]
> Hey @uroybd, thank you for submitting the issue.
> I am afraid there is not enough information for us to go on with here. Did you follow the setup instructions? Do regular previews (i.e. `HEADLESS_PREVIEW_LIVE = False`) work as expected?

No. `HEADLESS_PREVIEW_LIVE` is not on.

Here are some data that might help us to pinpoint the problem.

Current versions of relevant packages are:

- django==3.1.2
- wagtail==2.10.2
- wagtail-headless-preview==0.1.4

All the settings are exactly as shown in documentation.

Another thing is, in another project with similar setup but with following versions, it is working perfectly:

- django==3.0.8
- wagtail==2.9.2
- wagtail-headless-preview==0.1.4

**Comment by zerolab** [comment]
Ah, that is much better. I think this may have something to do with Django 3.1.x
Will try to set a test case and investigate in the next day or two

**Comment by uroybd** [comment]
I was just browsing wagtail's code.

The `PreviewOnEdit` view [here](https://github.com/wagtail/wagtail/blob/master/wagtail/admin/views/pages/preview.py) is actually calling the page's `make_preview_request` and serving that directly, without wrapping it in anything. We have to override this I guess.

**Comment by uroybd** [comment]
False Alarm. I'm extremely sorry for this. Somehow missed the subclassing mixin part.

**Comment by zerolab** [comment]
Glad it was not something more serious and you've managed to find the issue
