### ISSUE TITLE
Generating preview url dynamically, instead of static HEADLESS_PREVIEW_CLIENT_URLS

### ISSUE THREAD

**Issue by HsnVahedi** [torchbox/wagtail-headless-preview#18]
I'm using wagtail with next js. Here is the documentation for it's [preview mode](https://nextjs.org/docs/advanced-features/preview-mode).

I need to generate different preview urls for different pages. For example, when someone wants to see the Home page's preview, it should redirect to "FRONTEND/?slug=home" and when someone wants to see the Products page's preview, it should redirect to "FRONTEND/?slug=products".

Is it possible?

**Comment by gasman** [comment]
It should be possible to do this by overriding the `get_client_root_url` method on your page models:

https://github.com/torchbox/wagtail-headless-preview/blob/e16d10755e6846f03caf5ed805060444831745f9/wagtail_headless_preview/models.py#L67-L71

**Comment by HsnVahedi** [comment]
Thanks for your response! @gasman
