### ISSUE TITLE
What is the purpose of PagePreview.token ?

### ISSUE THREAD

**Issue by HsnVahedi** [torchbox/wagtail-headless-preview#19]
In documentation in "PagePreviewAPIViewSet.get_object", this line gets the "PagePreview" object:

`page_preview = PagePreview.objects.get(content_type=content_type, token=self.request.GET['token'])`

But it hasn't mentioned anything about how and when PagePreview objects should be created.

Do we have to create a PagePreview with a unique token for every page type?

What's the purpose of token?

**Comment by zerolab** [comment]
`PagePreview` instances are created on preview automatically: https://github.com/torchbox/wagtail-headless-preview/blob/master/wagtail_headless_preview/models.py#L51 and is an identifier that is used to fetch the correct preview object.

What is important is the fact that the token is used on /preview and should be used by whatever API to get the preview data based on it. The API shold not be concerned with the creation of `PagePreview` objects

The documentation does not need to go into the internals of how it does things, one can read the code if they are interested.

**Comment by HsnVahedi** [comment]
Thanks a lot! @zerolab

But `page_preview = PagePreview.objects.get(content_type=content_type, token=self.request.GET['token'])` needs the token to be provided as a GET parameter. How should the frontend application know the value of the generated token?

This `PagePreviewAPIViewSet` is meant to serve the frontend request, right?

**Comment by zerolab** [comment]
when you click preview, the preview page loads your defined preview URL in an iframe with its source as 

`PREVIEW_URL?content_type=app.modelname&token=id%3D15%3A1knmcT%3ABknOQKDurFquCaRuzhF4h4vq8B_lH1rpZ225sbd8trg` as you can see `token` is a query parameters.

it is up to your front-end application to do what it needs to do with that. The `client/index.html` example in the README takes the query parameters and passes them to the example API endpoint, which then knows how to handle them.

**Comment by HsnVahedi** [comment]
God bless you! @zerolab

Now, I understand the data passing mechanism. But why does it use `iframe`? Why doesn't it just redirect to the specified `PREVIEW_URL`?

Is it ok if I override `HeadlessPreviewMixin.serve_preview` to just redirect instead of rendering `wagtail_headless_preview/preview.html`?

**Comment by zerolab** [comment]
That is up to you as an implementer. The package is a building block that anyone can use in their own way

**Comment by HsnVahedi** [comment]
Finally, I connected the cms to my frontend (next js) service, thanks to your advices. @zerolab 

What I actually needed was a subset of features that this package offers:

- I didn't need the live preview feature.

- I didn't want wagtail to use `iframe`

I think another package with easier documentation that doesn't support these features would make the using of this package much easier.

It took almost a day for me to understand how to use it.

Is it ok if I create another package based on this one for the sake of a simpler learning curve?

**Comment by zerolab** [comment]
Hi @HsnVahedi 

1. live preview is not enabled by deafult. Instead it is an opt-in feature. You enabled it when you need to use it
2. not wanting to use `iframe` is a fair point. Do help with #15 to make it happen.

> I think another package with easier documentation that doesn't support these features would make the using of this package much easier.
> Is it ok if I create another package based on this one for the sake of a simpler learning curve?

That will make things even more confusing!! Instead, why don't you contribute pull requests to make documentation clearer and allow non-iframe usage (as per #15)?

> It took almost a day for me to understand how to use it.
I am sorry to hear that. As someone that already took the time to learn this, you are best placed to help improve the developer onboarding experience.
