### ISSUE TITLE
`HEADLESS_PREVIEW_CLIENT_URLS` are not loaded in Version 0.2.0

### ISSUE THREAD

**Issue by Schille** [torchbox/wagtail-headless-preview#26]
Thanks for publishing this package and the new version 0.2.0 recently.

After I updated the installed version of the package in our wagtail project to 0.2.0 I got the following error in the log during a preview:
```
Traceback (most recent call last):
  [...]
  File "/layers/[...]/python3.8/site-packages/wagtail_headless_preview/models.py", line 40, in get_client_root_url_from_site
    root_url = headless_preview_settings.CLIENT_URLS["default"].format(
KeyError: 'default'
```
I still use the old configuration `HEADLESS_PREVIEW_CLIENT_URLS` and I noticed that the old configuration style is actually handled in the code. However, it does not seem to work properly.

I would assume the issue in this line 
https://github.com/torchbox/wagtail-headless-preview/blob/167c3c732e265cb2cae149f4b06861bf9a9a7dea/src/wagtail_headless_preview/settings.py#L92
since `user_settings` is `None` at that point and `setting_in_user_settings` is subsequently checked in order to construct the settings.

The settings object gets instantiated here with a `None` for the `user_settings` variable:
https://github.com/torchbox/wagtail-headless-preview/blob/167c3c732e265cb2cae149f4b06861bf9a9a7dea/src/wagtail_headless_preview/settings.py#L119

The tests are loaded with `user_settings` value given and hence result in a positive outcome:
https://github.com/torchbox/wagtail-headless-preview/blob/167c3c732e265cb2cae149f4b06861bf9a9a7dea/tests/test_settings.py#L48-L49

I hope you'll find the time to look into it. If you need more information please let me know.

**Comment by zerolab** [comment]
@Schille opened #27 with a fix. Will make a new release shortly

**Comment by zerolab** [comment]
https://pypi.org/project/wagtail-headless-preview/0.2.1/ now out. Thank you
