### ISSUE TITLE
Live Previews do not work.

### ISSUE THREAD

**Issue by dopry** [torchbox/wagtail-headless-preview#31]
As far as I can tell in [wagtail_headless_prevew.models.HeadlessPreviewMixin.serve_preview](https://github.com/torchbox/wagtail-headless-preview/blob/f289aaf03170cd343a7345b4922a06b015052af1/src/wagtail_headless_preview/models.py#L102), use_live_preview is never true, even when ?live_preview=true is passed to the endpoint, which means the signal that triggers the subscription update is never sent.

I'm using the wagtail_grapple example to test, see my branch at https://github.com/dopry/wagtail-grapple/tree/fix/live-preview-subscriptions

**Comment by zerolab** [comment]
I've dropped that code as I am not using anywhere, and it broke at some point.
Also the new Wagtail 4.0 live preview just works

**Comment by dopry** [comment]
I noticed they started working in 4.x, thanks for taking the time to look into it.
