### ISSUE TITLE
Unique constraint error in create_page_preview

### ISSUE THREAD

**Issue by johncarter-phntm** [torchbox/wagtail-headless-preview#34]
`create_page_preview` is calling get_or_create without passing the non-unique values as defaults. This leads to a unique constraint error, eg 
`django.db.utils.IntegrityError: UNIQUE constraint failed: wagtail_headless_preview_pagepreview.token` if it's called twice when the signer returns the same value (eg if it's called twice in the same second).

https://github.com/torchbox/wagtail-headless-preview/blob/f87b2b5b430af8c578ad3b3dbef89b2567a7493c/src/wagtail_headless_preview/models.py#L64-L80

One solution would be pass defaults to get_or_create, but I think maybe it'd be better to call update_page_preview regardless?

**Comment by Scotchester** [comment]
Hi @johncarter-phntm,

Do you have a reliable way to reproduce this? My colleague reported that he was able to trigger this error in a way that would not seem to be caused by previews being created in rapid succession. I'm asking for more details, but here is how he described it:

> 1. Edit a page with preview panel enabled
> 2. Browse another section of the cms
> 3. Go back to edit the page in step 1

**Comment by johncarter-phntm** [comment]
@Scotchester in normal use, no, but my unit test in #35 reliably hits it.

I think if you generated 2 previews of the same page in the same second you'll hit it, due to use of TimestampSigner.
