### ISSUE TITLE
Adding value of content_panels or api_fields to the preview json result

### ISSUE THREAD

**Issue by fabio1079** [torchbox/wagtail-headless-preview#45]
Hi, I followed the base setup in [example guide](https://github.com/torchbox/wagtail-headless-preview#example) but the page_preview endpoint is not passing the content of the content_panels or api_fields to the json.

I took a look at the `PagePreview` model in the `PagePreviewAPIViewSet` and the data is present in the `content_json`, but once the `get_object()` is called at `listing_view()`, in `serializer.data` the value from content_panels or api_fields are not present.

The wagtail_headless_preview package has a serializer that get these values or should I create my own serailizer to get this data ?

**Comment by zerolab** [comment]
👋
wagtail_headless_preview doesn't provide a serialiser as everyone's needs are slightly different. e.g. lots use this with a GraphQL endpoint
So best to roll your own

**Comment by fabio1079** [comment]
A yes, by using the GraphQL endpoint is possible to get the preview model data, tried it here and worked pretty well, wagtail_headless_preview called the front passing the token of the preview page and the front fetched the data using GraphQL.
Thanks for point a way to get the data :+1:
